import 'package:flutter/material.dart';

class Products {
  final String image, productName, productWeight, productType;
  final int price;
  final Color color;
  late bool isFavorite;
  late bool isWishlist;
  late int count;
  late double rating;

  Products({
    required this.image,
    required this.productName,
    required this.productWeight,
    required this.productType,
    required this.price,
    required this.color,
    required this.isFavorite,
    required this.isWishlist,
    required this.count,
    required this.rating,
  });
}

final productsList = [
  Products(
    image: "mango.png",
    productName: "Mango",
    productWeight: "1kg",
    productType: "fruit",
    price: 400,
    color: Colors.yellow,
    isFavorite: false,
    isWishlist: false,
    count: 1,
    rating: 3.8,
  ),
  Products(
    image: "tomato.png",
    productName: "Tomato",
    productWeight: "1kg",
    productType: "vegetable",
    price: 800,
    color: Colors.red,
    isFavorite: false,
    isWishlist: false,
    count: 1,
    rating: 3.6,
  ),
  Products(
    image: "cabbage.png",
    productName: "Cabbage",
    productWeight: "2kg",
    productType: "vegetable",
    price: 900,
    color: Colors.green,
    isFavorite: false,
    isWishlist: false,
    count: 1,
    rating: 4.0,
  ),
  Products(
    image: "banana.png",
    productName: "Banana",
    productWeight: "3kg",
    productType: "fruit",
    price: 500,
    color: Colors.yellow,
    isFavorite: false,
    isWishlist: false,
    count: 1,
    rating: 4.5,
  ),
  Products(
    image: "carrot.png",
    productName: "Carrot",
    productWeight: "0.5kg",
    productType: "vegetable",
    price: 600,
    color: Colors.orange,
    isFavorite: false,
    isWishlist: false,
    count: 1,
    rating: 3.7,
  ),
  Products(
    image: "beetroot.png",
    productName: "Beetroot",
    productWeight: "1kg",
    productType: "vegetable",
    price: 700,
    color: Colors.pink,
    isFavorite: false,
    isWishlist: false,
    count: 1,
    rating: 3.4,
  ),
  Products(
    image: "pineapple.png",
    productName: "Pineapple",
    productWeight: "1kg",
    productType: "fruit",
    price: 800,
    color: Colors.yellow,
    isFavorite: false,
    isWishlist: false,
    count: 1,
    rating: 4.2,
  ),
  Products(
    image: "capsicum.png",
    productName: "Capsicum",
    productWeight: "1kg",
    productType: "vegetable",
    price: 700,
    color: Colors.green,
    isFavorite: false,
    isWishlist: false,
    count: 1,
    rating: 4.1,
  ),
  Products(
    image: "grapes.png",
    productName: "Grapes",
    productWeight: "0.5kg",
    productType: "fruit",
    price: 200,
    color: Colors.purple,
    isFavorite: false,
    isWishlist: false,
    count: 1,
    rating: 3.5,
  ),
];
